### PR TITLE
Message subclassing

### PR DESCRIPTION
**Pull request by wishdev**
These are adds/mods to allow for the subclassing of DripDrop::Message to add additional functionality to the message itself if needed.

The example is a little contrived but it does show the subclassing of the Message class.

### CODE REVIEW

**Comment by andrewvc** [comment]
Thanks for the patch! Looks good, it's definitely going in but I think it could be filled out a little more. What're your thoughts on the following ideas?
1. Default messages for outgoing sockets, so you can send messages using the hash notation after setting a default message.
2. Ability to define the default in the handler options e.g. zmq_subscribe(addr,:bind,:default_message_class => Klass)
3. Specs. I recently checked in specs for the message class and Node. I'd like to have as much test coverage as possible.
4. Auto-detection of message class when reading messages (maybe :head => {'__mclass' => Klass})

**Comment by wishdev** [comment]
In order
1. Don't quite understand that one - are you saying sort of like a default response?
2. Makes sense
3. More than happy to add specs to it
4. I actually prefer this idea but at the same time I not sure we want to weigh down the speed of someone wanting just nice simple messages to pass through (i.e. someone using DripDrop::Message for everything).

Let me pull this back and have another run at it over the weekend.....

John

**Comment by andrewvc** [comment]
Oh, for #1 I meant a default format in case people are using the hash syntax to sent messages. Something like:
    push = zmq_push(addr, :connect, :default_message_class => TimestampedMessage)
    push.send_message(:name => '...', :head => {}, :body => '...')

For #4, I agree, I'd rather not waste network bandwidth and cpu cycles. However, I would like a single socket to be able to receive heterogenous message classes. Maybe we could make it configurable, both globally and per socket. I'd actually be inclined to default it to auto. My suspicion is that the processing overhead will be minimal. If I have time I'll run some benchmarks this weekend.

Thoughts?

**Comment by andrewvc** [comment]
It's in!

**Pull request merged**
